<?php

namespace Circlical\TailwindForms\Form\View\Helper;

use Laminas\Form\ElementInterface;

class FormText extends \Laminas\Form\View\Helper\FormText
{
    public function render(ElementInterface $element): string
    {
        return parent::render($element);
    }

    protected function prepareAttributes(array $attributes): array
    {
        $attributes = parent::prepareAttributes($attributes); // TODO: Change the autogenerated stub
        if ($attributes['value'] === null) {
            unset($attributes['value']);
        }

        return $attributes;
    }
}

